import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ko' | 'ja' | 'zh' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Hero Section
    'hero.title': 'K-VVIP Limousine',
    'hero.headline1': 'First Class on the Road',
    'hero.headline2': 'Premium Concierge in Korea',
    'hero.subheadline': 'Safe, Private, and Comfortable travel for Medical Recovery & VVIP Tours',
    'hero.badge1': 'English-Speaking Drivers',
    'hero.badge2': '24/7 Available',
    'hero.badge3': 'Certified & Professional',
    'hero.cta.book': 'Book Now',
    'hero.cta.chat': 'Chat on WhatsApp',

    // Service Choice
    'service.title': 'Choose Your Premium Experience',
    'service.subtitle': 'Tailored services for your unique needs in Korea',
    'service.medical.title': 'Medical Care & Recovery',
    'service.medical.description': 'Safe pickup, driver waiting during surgery, sterilized vehicle, door-to-door escort with compassionate care for your medical journey.',
    'service.medical.feature1': 'Professional Medical Transport',
    'service.medical.feature2': 'Sterilized & Sanitized Vehicle',
    'service.medical.feature3': 'Driver Standby During Procedures',
    'service.medical.feature4': 'Comfortable Post-Surgery Care',
    'service.tour.title': 'VVIP Private Tour',
    'service.tour.description': 'Customized schedule, spacious for golf/shopping, English-speaking driver, and premium experiences tailored to your lifestyle.',
    'service.tour.feature1': 'Fully Customizable Itinerary',
    'service.tour.feature2': 'English-Speaking Professional Driver',
    'service.tour.feature3': 'Spacious Luxury Interior',
    'service.tour.feature4': 'Perfect for Golf, Shopping & Tours',
    'service.button': 'Learn More',

    // Vehicle Showcase
    'vehicle.title': 'The',
    'vehicle.name': 'Kia Carnival Hi-Limousine',
    'vehicle.subtitle': "Experience unmatched luxury with Korea's premier VIP vehicle",
    'vehicle.feature1.title': 'VIP Ottoman Reclining Seats',
    'vehicle.feature1.description': 'First-class comfort with adjustable luxury seating',
    'vehicle.feature2.title': '27-inch Entertainment TV',
    'vehicle.feature2.description': 'Premium in-car entertainment system',
    'vehicle.feature3.title': 'Free Wi-Fi',
    'vehicle.feature3.description': 'Stay connected throughout your journey',
    'vehicle.feature4.title': 'Privacy Curtains',
    'vehicle.feature4.description': 'Complete privacy for your comfort',
    'vehicle.feature5.title': 'Large Trunk Capacity',
    'vehicle.feature5.description': 'Ample space for luggage, golf bags, shopping',
    'vehicle.note': '✨ Professionally maintained and sanitized before every journey',

    // Pricing
    'pricing.title': 'Transparent',
    'pricing.highlight': 'Pricing',
    'pricing.subtitle': 'Choose the perfect package for your needs. All prices in USD.',
    'pricing.plan1.name': 'Airport Transfer',
    'pricing.plan1.note': 'Starting from',
    'pricing.plan1.feature1': 'Meet & Greet Service',
    'pricing.plan1.feature2': 'Direct to/from Airport',
    'pricing.plan1.feature3': 'Flight Tracking',
    'pricing.plan1.feature4': 'Luggage Assistance',
    'pricing.plan1.feature5': 'One-way or Round Trip',
    'pricing.plan2.name': 'Half Day Care',
    'pricing.plan2.note': '5 Hours',
    'pricing.plan2.feature1': 'Up to 5 Hours Service',
    'pricing.plan2.feature2': 'Waiting Time Included',
    'pricing.plan2.feature3': 'Perfect for Medical Visits',
    'pricing.plan2.feature4': 'Flexible Schedule',
    'pricing.plan2.feature5': 'Professional Care',
    'pricing.plan3.name': 'Full Day Tour',
    'pricing.plan3.note': '10 Hours',
    'pricing.plan3.badge': 'Best Value',
    'pricing.plan3.feature1': 'Up to 10 Hours Service',
    'pricing.plan3.feature2': 'Gas & Tolls Included',
    'pricing.plan3.feature3': 'Customized Itinerary',
    'pricing.plan3.feature4': 'English-Speaking Driver',
    'pricing.plan3.feature5': 'Maximum Flexibility',
    'pricing.button': 'Book Now',
    'pricing.disclaimer': '* Prices may vary based on distance, time, and specific requirements. Contact us for a customized quote tailored to your needs.',

    // Social Proof
    'social.title': 'Trusted by',
    'social.highlight': 'VIP Travelers',
    'social.subtitle': "Don't just take our word for it - hear from our satisfied clients",
    'social.stat1.number': '5,000+',
    'social.stat1.label': 'Happy Clients',
    'social.stat2.number': '10+',
    'social.stat2.label': 'Years Experience',
    'social.stat3.number': '4.9/5',
    'social.stat3.label': 'Average Rating',
    'social.stat4.number': '24/7',
    'social.stat4.label': 'Support Available',
    'social.review1.text': 'Best driver for my surgery trip. The care and attention during my recovery period was exceptional. Highly recommend!',
    'social.review1.name': 'Sarah Johnson',
    'social.review1.location': 'United States',
    'social.review2.text': 'So comfortable for my family. The spacious interior and entertainment system kept my kids happy throughout the tour.',
    'social.review2.name': 'Michael Chen',
    'social.review2.location': 'Singapore',
    'social.review3.text': 'Professional, punctual, and luxurious. The English-speaking driver made navigating Korea so much easier. Will use again!',
    'social.review3.name': 'Emma Wilson',
    'social.review3.location': 'United Kingdom',
    'social.review4.text': 'Perfect for my golf trip. Plenty of space for clubs and bags. The driver knew all the best courses and restaurants.',
    'social.review4.name': 'David Park',
    'social.review4.location': 'Australia',
    'social.trust1.label': 'Verified on',
    'social.trust1.name': 'Google Reviews',
    'social.trust2.label': 'Featured on',
    'social.trust2.name': 'TripAdvisor',
    'social.trust3.label': 'Trusted by',
    'social.trust3.name': 'Medical Tourism Association',

    // Footer
    'footer.description': 'Premium concierge service providing luxury transportation for medical tourists and VIP travelers in Korea.',
    'footer.quicklinks': 'Quick Links',
    'footer.link1': 'About Us',
    'footer.link2': 'Services',
    'footer.link3': 'Pricing',
    'footer.link4': 'Book Now',
    'footer.link5': 'FAQ',
    'footer.services': 'Our Services',
    'footer.service1': 'Airport Transfer',
    'footer.service2': 'Medical Care Transport',
    'footer.service3': 'VVIP Private Tours',
    'footer.service4': 'Golf Tours',
    'footer.service5': 'Shopping Tours',
    'footer.contact': 'Contact Us',
    'footer.location': 'Seoul, South Korea',
    'footer.copyright': '© 2024 K-VVIP Limousine. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',

    // Floating Chat
    'chat.inquiry': 'Inquiry',

    // VIP Perks
    'vip.title': 'Only for Our VIP Guests',
    'vip.subtitle': 'Experience Korea beyond just transportation',
    'vip.perk1.title': 'Recovery Kit',
    'vip.perk1.description': 'Free welcome recovery kit including anti-swelling tea, cooling eye mask, and more',
    'vip.perk2.title': 'No-Wait Dining',
    'vip.perk2.description': 'Skip the line at famous restaurants - we handle reservations (Ganjang Gejang, Korean BBQ Omakase)',
    'vip.perk3.title': 'Free Botox & Skin Laser',
    'vip.perk3.description': 'Complimentary treatment at Seoul\'s top clinics - one free procedure per person'
  },
  ko: {
    // Hero Section
    'hero.title': 'K-VVIP 리무진',
    'hero.headline1': '도로 위의 퍼스트 클래스',
    'hero.headline2': '한국의 프리미엄 컨시어지',
    'hero.subheadline': '의료 회복 및 VVIP 투어를 위한 안전하고 프라이빗하며 편안한 여행',
    'hero.badge1': '영어 가능 기사',
    'hero.badge2': '24시간 운영',
    'hero.badge3': '인증된 전문가',
    'hero.cta.book': '예약하기',
    'hero.cta.chat': '왓츠앱 채팅',

    // Service Choice
    'service.title': '프리미엄 경험을 선택하세요',
    'service.subtitle': '한국에서의 특별한 니즈에 맞춘 맞춤형 서비스',
    'service.medical.title': '의료 케어 & 회복',
    'service.medical.description': '안전한 픽업, 수술 중 대기, 멸균 차량, 문앞까지 에스코트와 함께 의료 여정을 따뜻하게 케어합니다.',
    'service.medical.feature1': '전문 의료 운송',
    'service.medical.feature2': '멸균 및 소독 차량',
    'service.medical.feature3': '시술 중 기사 대기',
    'service.medical.feature4': '편안한 수술 후 케어',
    'service.tour.title': 'VVIP 프라이빗 투어',
    'service.tour.description': '맞춤형 일정, 골프/쇼핑에 넉넉한 공간, 영어 가능 기사, 그리고 당신의 라이프스타일에 맞춘 프리미엄 경험.',
    'service.tour.feature1': '완전 맞춤형 일정',
    'service.tour.feature2': '영어 가능 전문 기사',
    'service.tour.feature3': '넉넉한 럭셔리 인테리어',
    'service.tour.feature4': '골프, 쇼핑 및 투어에 완벽',
    'service.button': '더 알아보기',

    // Vehicle Showcase
    'vehicle.title': '',
    'vehicle.name': '기아 카니발 하이리무진',
    'vehicle.subtitle': '한국 최고의 VIP 차량으로 비교할 수 없는 럭셔리를 경험하세요',
    'vehicle.feature1.title': 'VIP 오토만 리클라이닝 시트',
    'vehicle.feature1.description': '조절 가능한 럭셔리 시트로 퍼스트 클래스 편안함',
    'vehicle.feature2.title': '27인치 엔터테인먼트 TV',
    'vehicle.feature2.description': '프리미엄 차량 엔터테인먼트 시스템',
    'vehicle.feature3.title': '무료 Wi-Fi',
    'vehicle.feature3.description': '여정 내내 인터넷 연결',
    'vehicle.feature4.title': '프라이버시 커튼',
    'vehicle.feature4.description': '편안함을 위한 완벽한 프라이버시',
    'vehicle.feature5.title': '대용량 트렁크',
    'vehicle.feature5.description': '짐, 골프백, 쇼핑백을 위한 넉넉한 공간',
    'vehicle.note': '✨ 모든 여정 전 전문적으로 관리 및 소독',

    // Pricing
    'pricing.title': '투명한',
    'pricing.highlight': '가격',
    'pricing.subtitle': '필요에 맞는 완벽한 패키지를 선택하세요. 모든 가격은 USD입니다.',
    'pricing.plan1.name': '공항 픽업/샌딩',
    'pricing.plan1.note': '시작 가격',
    'pricing.plan1.feature1': '미트 & 그리트 서비스',
    'pricing.plan1.feature2': '공항 직행 왕복',
    'pricing.plan1.feature3': '비행기 추적',
    'pricing.plan1.feature4': '짐 도움',
    'pricing.plan1.feature5': '편도 또는 왕복',
    'pricing.plan2.name': '반나절 케어',
    'pricing.plan2.note': '5시간',
    'pricing.plan2.feature1': '최대 5시간 서비스',
    'pricing.plan2.feature2': '대기 시간 포함',
    'pricing.plan2.feature3': '의료 방문에 완벽',
    'pricing.plan2.feature4': '유연한 일정',
    'pricing.plan2.feature5': '전문 케어',
    'pricing.plan3.name': '하루 종일 투어',
    'pricing.plan3.note': '10시간',
    'pricing.plan3.badge': '베스트 가치',
    'pricing.plan3.feature1': '최대 10시간 서비스',
    'pricing.plan3.feature2': '유류비 및 통행료 포함',
    'pricing.plan3.feature3': '맞춤형 일정',
    'pricing.plan3.feature4': '영어 가능 기사',
    'pricing.plan3.feature5': '최대 유연성',
    'pricing.button': '예약하기',
    'pricing.disclaimer': '* 가격은 거리, 시간 및 특정 요구 사항에 따라 달라질 수 있습니다. 맞춤형 견적은 문의하세요.',

    // Social Proof
    'social.title': '신뢰받는',
    'social.highlight': 'VIP 여행자들',
    'social.subtitle': '우리의 말만 믿지 마시고 만족한 고객들의 이야기를 들어보세요',
    'social.stat1.number': '5,000+',
    'social.stat1.label': '만족한 고객',
    'social.stat2.number': '10+',
    'social.stat2.label': '년 경험',
    'social.stat3.number': '4.9/5',
    'social.stat3.label': '평균 평점',
    'social.stat4.number': '24/7',
    'social.stat4.label': '지원 가능',
    'social.review1.text': '수술 여행에 최고의 기사님. 회복 기간 동안의 케어와 배려가 탁월했습니다. 강력 추천!',
    'social.review1.name': '사라 존슨',
    'social.review1.location': '미국',
    'social.review2.text': '가족과 함께 너무 편안했어요. 넓은 실내와 엔터테인먼트 시스템이 아이들을 투어 내내 즐겁게 해줬어요.',
    'social.review2.name': '마이클 첸',
    'social.review2.location': '싱가포르',
    'social.review3.text': '전문적이고, 시간 정확하고, 럭셔리합니다. 영어 가능한 기사님이 한국 여행을 훨씬 쉽게 만들어줬어요. 다시 이용할게요!',
    'social.review3.name': '엠마 윌슨',
    'social.review3.location': '영국',
    'social.review4.text': '골프 여행에 완벽했어요. 클럽과 가방을 위한 충분한 공간. 기사님이 최고의 코스와 레스토랑을 다 알고 계셨어요.',
    'social.review4.name': '데이비드 박',
    'social.review4.location': '호주',
    'social.trust1.label': '인증됨',
    'social.trust1.name': '구글 리뷰',
    'social.trust2.label': '추천됨',
    'social.trust2.name': '트립어드바이저',
    'social.trust3.label': '신뢰받음',
    'social.trust3.name': '메디컬 투어리즘 협회',

    // Footer
    'footer.description': '한국의 의료 관광객 및 VIP 여행자를 위한 프리미엄 컨시어지 럭셔리 운송 서비스.',
    'footer.quicklinks': '빠른 링크',
    'footer.link1': '회사 소개',
    'footer.link2': '서비스',
    'footer.link3': '가격',
    'footer.link4': '예약하기',
    'footer.link5': '자주 묻는 질문',
    'footer.services': '서비스',
    'footer.service1': '공항 픽업/샌딩',
    'footer.service2': '의료 케어 운송',
    'footer.service3': 'VVIP 프라이빗 투어',
    'footer.service4': '골프 투어',
    'footer.service5': '쇼핑 투어',
    'footer.contact': '연락처',
    'footer.location': '서울, 대한민국',
    'footer.copyright': '© 2024 K-VVIP 리무진. 모든 권리 보유.',
    'footer.privacy': '개인정보 보호정책',
    'footer.terms': '서비스 약관',
    'footer.cookies': '쿠키 정책',

    // Floating Chat
    'chat.inquiry': '문의하기',

    // VIP Perks
    'vip.title': '우리 VIP 손님만을 위한 혜택',
    'vip.subtitle': '교통만이 아닌 한국을 경험하세요',
    'vip.perk1.title': '회복 키트',
    'vip.perk1.description': '붓기차, 쿨링 안대 등 웰컴 회복 키트 무료 제공',
    'vip.perk2.title': '대기 없는 식사',
    'vip.perk2.description': '유명 맛집 웨이팅/예약 대행 (간장게장, 한우 오마카세)',
    'vip.perk3.title': '보톡스, 스킨레이저 무료제공',
    'vip.perk3.description': '서울에서 가장 잘 하는 병원에서 1인 무료 시술 제공'
  },
  ja: {
    // Hero Section
    'hero.title': 'K-VVIPリムジン',
    'hero.headline1': '道路上のファーストクラス',
    'hero.headline2': '韓国のプレミアムコンシェルジュ',
    'hero.subheadline': '医療回復とVVIPツアーのための安全でプライベートで快適な旅行',
    'hero.badge1': '英語対応ドライバー',
    'hero.badge2': '24時間利用可能',
    'hero.badge3': '認定プロフェッショナル',
    'hero.cta.book': '予約する',
    'hero.cta.chat': 'WhatsAppでチャット',

    // Service Choice
    'service.title': 'プレミアム体験をお選びください',
    'service.subtitle': '韓国でのお客様固有のニーズに合わせたサービス',
    'service.medical.title': '医療ケア＆回復',
    'service.medical.description': '安全な送迎、手術中のドライバー待機、滅菌車両、医療旅行のための思いやりあるドアツードアのエスコート。',
    'service.medical.feature1': 'プロフェッショナル医療輸送',
    'service.medical.feature2': '滅菌＆消毒済み車両',
    'service.medical.feature3': '処置中のドライバー待機',
    'service.medical.feature4': '快適な術後ケア',
    'service.tour.title': 'VVIPプライベートツアー',
    'service.tour.description': 'カスタマイズされたスケジュール、ゴルフ/ショッピングに広々とした空間、英語対応ドライバー、ライフスタイルに合わせたプレミアム体験。',
    'service.tour.feature1': '完全カスタマイズ可能な旅程',
    'service.tour.feature2': '英語対応プロフェッショナルドライバー',
    'service.tour.feature3': '広々としたラグジュアリーインテリア',
    'service.tour.feature4': 'ゴルフ、ショッピング、ツアーに最適',
    'service.button': '詳細を見る',

    // Vehicle Showcase
    'vehicle.title': '',
    'vehicle.name': '起亜カーニバル ハイリムジン',
    'vehicle.subtitle': '韓国最高のVIP車両で比類なき贅沢を体験',
    'vehicle.feature1.title': 'VIPオットマンリクライニングシート',
    'vehicle.feature1.description': '調整可能な高級シートでファーストクラスの快適さ',
    'vehicle.feature2.title': '27インチエンターテインメントTV',
    'vehicle.feature2.description': 'プレミアム車内エンターテインメントシステム',
    'vehicle.feature3.title': '無料Wi-Fi',
    'vehicle.feature3.description': '旅行中も常に接続',
    'vehicle.feature4.title': 'プライバシーカーテン',
    'vehicle.feature4.description': '快適さのための完全なプライバシー',
    'vehicle.feature5.title': '大容量トランク',
    'vehicle.feature5.description': '荷物、ゴルフバッグ、ショッピングのための十分なスペース',
    'vehicle.note': '✨ 毎回の旅行前にプロフェッショナルに整備および消毒',

    // Pricing
    'pricing.title': '透明な',
    'pricing.highlight': '価格',
    'pricing.subtitle': 'ニーズに合った完璧なパッケージをお選びください。すべての価格はUSDです。',
    'pricing.plan1.name': '空港送迎',
    'pricing.plan1.note': '開始価格',
    'pricing.plan1.feature1': 'ミート＆グリートサービス',
    'pricing.plan1.feature2': '空港直行往復',
    'pricing.plan1.feature3': 'フライト追跡',
    'pricing.plan1.feature4': '荷物アシスタンス',
    'pricing.plan1.feature5': '片道または往復',
    'pricing.plan2.name': '半日ケア',
    'pricing.plan2.note': '5時間',
    'pricing.plan2.feature1': '最大5時間サービス',
    'pricing.plan2.feature2': '待機時間込み',
    'pricing.plan2.feature3': '医療訪問に最適',
    'pricing.plan2.feature4': 'フレキシブルスケジュール',
    'pricing.plan2.feature5': 'プロフェッショナルケア',
    'pricing.plan3.name': '終日ツアー',
    'pricing.plan3.note': '10時間',
    'pricing.plan3.badge': 'ベストバリュー',
    'pricing.plan3.feature1': '最大10時間サービス',
    'pricing.plan3.feature2': 'ガス＆通行料込み',
    'pricing.plan3.feature3': 'カスタマイズされた旅程',
    'pricing.plan3.feature4': '英語対応ドライバー',
    'pricing.plan3.feature5': '最大の柔軟性',
    'pricing.button': '予約する',
    'pricing.disclaimer': '* 価格は距離、時間、および特定の要件に基づいて異なる場合があります。カスタマイズされた見積もりについてはお問い合わせください。',

    // Social Proof
    'social.title': '信頼される',
    'social.highlight': 'VIP旅行者',
    'social.subtitle': '私たちの言葉だけでなく、満足したクライアントの声をお聞きください',
    'social.stat1.number': '5,000+',
    'social.stat1.label': '満足したクライアント',
    'social.stat2.number': '10+',
    'social.stat2.label': '年の経験',
    'social.stat3.number': '4.9/5',
    'social.stat3.label': '平均評価',
    'social.stat4.number': '24/7',
    'social.stat4.label': 'サポート利用可能',
    'social.review1.text': '手術旅行に最高のドライバー。回復期間中のケアと配慮が素晴らしかった。強くお勧めします！',
    'social.review1.name': 'サラ・ジョンソン',
    'social.review1.location': 'アメリカ',
    'social.review2.text': '家族と一緒にとても快適でした。広々とした室内とエンターテインメントシステムが子供たちをツアー中ずっと楽しませてくれました。',
    'social.review2.name': 'マイケル・チェン',
    'social.review2.location': 'シンガポール',
    'social.review3.text': 'プロフェッショナルで、時間厳守で、豪華。英語対応ドライバーが韓国のナビゲーションをずっと簡単にしてくれました。また利用します！',
    'social.review3.name': 'エマ・ウィルソン',
    'social.review3.location': 'イギリス',
    'social.review4.text': 'ゴルフ旅行に完璧でした。クラブとバッグのための十分なスペース。ドライバーが最高のコースとレストランを全て知っていました。',
    'social.review4.name': 'デビッド・パーク',
    'social.review4.location': 'オーストラリア',
    'social.trust1.label': '認証済み',
    'social.trust1.name': 'Googleレビュー',
    'social.trust2.label': '掲載',
    'social.trust2.name': 'トリップアドバイザー',
    'social.trust3.label': '信頼される',
    'social.trust3.name': 'メディカルツーリズム協会',

    // Footer
    'footer.description': '韓国の医療観光客とVIP旅行者のためのプレミアムコンシェルジュ高級輸送サービス。',
    'footer.quicklinks': 'クイックリンク',
    'footer.link1': '会社概要',
    'footer.link2': 'サービス',
    'footer.link3': '価格',
    'footer.link4': '予約する',
    'footer.link5': 'よくある質問',
    'footer.services': 'サービス',
    'footer.service1': '空港送迎',
    'footer.service2': '医療ケア輸送',
    'footer.service3': 'VVIPプライベートツアー',
    'footer.service4': 'ゴルフツアー',
    'footer.service5': 'ショッピングツアー',
    'footer.contact': 'お問い合わせ',
    'footer.location': 'ソウル、韓国',
    'footer.copyright': '© 2024 K-VVIPリムジン。全著作権所有。',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.cookies': 'クッキーポリシー',

    // Floating Chat
    'chat.inquiry': 'お問い合わせ',

    // VIP Perks
    'vip.title': '私たちのVIPゲストのみの特典',
    'vip.subtitle': '輸送だけではなく、韓国を体験してください',
    'vip.perk1.title': '回復キット',
    'vip.perk1.description': '腫れ止めティーや冷却マスクなど、回復キットを無料で提供します',
    'vip.perk2.title': '待ち時間なしのダイニング',
    'vip.perk2.description': '有名レストランで待ち時間を省きます - 私たちが予約を手伝います (ガンジャンゲジャング、韓国 BBQ オマカゼ)',
    'vip.perk3.title': '無料ボトックス & スキンレーザー',
    'vip.perk3.description': 'ソウルのトップクリニックで無料で提供される治療 - 1人あたり1回無料手順'
  },
  zh: {
    // Hero Section
    'hero.title': 'K-VVIP豪华轿车',
    'hero.headline1': '道路上的头等舱',
    'hero.headline2': '韩国高级礼宾服务',
    'hero.subheadline': '为医疗康复和VIP旅游提供安全、私密和舒适的旅行',
    'hero.badge1': '英语司机',
    'hero.badge2': '24/7可用',
    'hero.badge3': '认证专业人员',
    'hero.cta.book': '立即预订',
    'hero.cta.chat': 'WhatsApp聊天',

    // Service Choice
    'service.title': '选择您的高级体验',
    'service.subtitle': '为您在韩国的独特需求量身定制的服务',
    'service.medical.title': '医疗护理与康复',
    'service.medical.description': '安全接送、手术期间司机等候、消毒车辆、门到门护送，为您的医疗旅程提供贴心护理。',
    'service.medical.feature1': '专业医疗运输',
    'service.medical.feature2': '灭菌和消毒车辆',
    'service.medical.feature3': '手术期间司机待命',
    'service.medical.feature4': '舒适的术后护理',
    'service.tour.title': 'VVIP私人游览',
    'service.tour.description': '定制行程，为高尔夫/购物提供宽敞空间，英语司机，以及根据您的生活方式定制的高级体验。',
    'service.tour.feature1': '完全可定制的行程',
    'service.tour.feature2': '英语专业司机',
    'service.tour.feature3': '宽敞豪华内饰',
    'service.tour.feature4': '非常适合高尔夫、购物和旅游',
    'service.button': '了解更多',

    // Vehicle Showcase
    'vehicle.title': '',
    'vehicle.name': '起亚嘉华豪华轿车',
    'vehicle.subtitle': '体验韩国顶级VIP车辆的无与伦比的奢华',
    'vehicle.feature1.title': 'VIP脚踏式躺椅座椅',
    'vehicle.feature1.description': '可调节豪华座椅的头等舱舒适',
    'vehicle.feature2.title': '27英寸娱乐电视',
    'vehicle.feature2.description': '高级车载娱乐系统',
    'vehicle.feature3.title': '免费Wi-Fi',
    'vehicle.feature3.description': '全程保持连接',
    'vehicle.feature4.title': '隐私窗帘',
    'vehicle.feature4.description': '为您的舒适提供完全隐私',
    'vehicle.feature5.title': '大容量行李箱',
    'vehicle.feature5.description': '充足的行李、高尔夫球袋、购物空间',
    'vehicle.note': '✨ 每次旅程前专业维护和消毒',

    // Pricing
    'pricing.title': '透明',
    'pricing.highlight': '定价',
    'pricing.subtitle': '选择适合您需求的完美套餐。所有价格以美元计。',
    'pricing.plan1.name': '机场接送',
    'pricing.plan1.note': '起价',
    'pricing.plan1.feature1': '迎接和问候服务',
    'pricing.plan1.feature2': '直达机场往返',
    'pricing.plan1.feature3': '航班跟踪',
    'pricing.plan1.feature4': '行李协助',
    'pricing.plan1.feature5': '单程或往返',
    'pricing.plan2.name': '半日护理',
    'pricing.plan2.note': '5小时',
    'pricing.plan2.feature1': '最多5小时服务',
    'pricing.plan2.feature2': '包括等待时间',
    'pricing.plan2.feature3': '非常适合医疗访问',
    'pricing.plan2.feature4': '灵活的时间表',
    'pricing.plan2.feature5': '专业护理',
    'pricing.plan3.name': '全日游览',
    'pricing.plan3.note': '10小时',
    'pricing.plan3.badge': '最佳价值',
    'pricing.plan3.feature1': '最多10小时服务',
    'pricing.plan3.feature2': '包括油费和通行费',
    'pricing.plan3.feature3': '定制行程',
    'pricing.plan3.feature4': '英语司机',
    'pricing.plan3.feature5': '最大灵活性',
    'pricing.button': '立即预订',
    'pricing.disclaimer': '* 价格可能因距离、时间和具体要求而有所不同。联系我们获取根据您的需求定制的报价。',

    // Social Proof
    'social.title': '受信任的',
    'social.highlight': 'VIP旅行者',
    'social.subtitle': '不要只听我们的话 - 听听我们满意客户的声音',
    'social.stat1.number': '5,000+',
    'social.stat1.label': '满意的客户',
    'social.stat2.number': '10+',
    'social.stat2.label': '年经验',
    'social.stat3.number': '4.9/5',
    'social.stat3.label': '平均评分',
    'social.stat4.number': '24/7',
    'social.stat4.label': '支持可用',
    'social.review1.text': '我手术旅行的最佳司机。康复期间的护理和关注非常出色。强烈推荐！',
    'social.review1.name': '莎拉·约翰逊',
    'social.review1.location': '美国',
    'social.review2.text': '对我的家人来说非常舒适。宽敞的内部和娱乐系统让我的孩子在整个旅程中都很开心。',
    'social.review2.name': '迈克尔·陈',
    'social.review2.location': '新加坡',
    'social.review3.text': '专业、准时、豪华。英语司机让在韩国导航变得更容易。会再次使用！',
    'social.review3.name': '艾玛·威尔逊',
    'social.review3.location': '英国',
    'social.review4.text': '非常适合我的高尔夫之旅。有足够的空间放俱乐部和包。司机知道所有最好的球场和餐厅。',
    'social.review4.name': '大卫·帕克',
    'social.review4.location': '澳大利亚',
    'social.trust1.label': '已验证',
    'social.trust1.name': '谷歌评论',
    'social.trust2.label': '特色',
    'social.trust2.name': '猫途鹰',
    'social.trust3.label': '受信任',
    'social.trust3.name': '医疗旅游协会',

    // Footer
    'footer.description': '为韩国医疗游客和VIP旅行者提供豪华运输服务的高级礼宾服务。',
    'footer.quicklinks': '快速链接',
    'footer.link1': '关于我们',
    'footer.link2': '服务',
    'footer.link3': '定价',
    'footer.link4': '立即预订',
    'footer.link5': '常见问题',
    'footer.services': '我们的服务',
    'footer.service1': '机场接送',
    'footer.service2': '医疗护理运输',
    'footer.service3': 'VVIP私人游览',
    'footer.service4': '高尔夫游览',
    'footer.service5': '购物游览',
    'footer.contact': '联系我们',
    'footer.location': '首尔，韩国',
    'footer.copyright': '© 2024 K-VVIP豪华轿车。版权所有。',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.cookies': 'Cookie政策',

    // Floating Chat
    'chat.inquiry': '咨询',

    // VIP Perks
    'vip.title': '仅限我们的VIP客人',
    'vip.subtitle': '体验韩国不仅仅是交通',
    'vip.perk1.title': '恢复包',
    'vip.perk1.description': '免费提供欢迎恢复包，包括消肿茶、冷却眼罩等',
    'vip.perk2.title': '无需等待用餐',
    'vip.perk2.description': '跳过著名餐厅的排队 - 我们会处理预订（甘酱蟹、韩国烧烤套餐）',
    'vip.perk3.title': '免费保妥克斯 & 皮肤激光',
    'vip.perk3.description': '首尔顶级诊所提供的免费治疗 - 每人一次免费疗程'
  },
  th: {
    // Hero Section
    'hero.title': 'K-VVIPลิมูซีน',
    'hero.headline1': 'ชั้นหนึ่งบนท้องถนน',
    'hero.headline2': 'คอนเซียร์จพรีเมียมในเกาหลี',
    'hero.subheadline': 'การเดินทางที่ปลอดภัย ส่วนตัว และสะดวกสบายสำหรับการฟื้นตัวทางการแพทย์และทัวร์ VIP',
    'hero.badge1': 'คนขับพูดภาษาอังกฤษได้',
    'hero.badge2': 'บริการตลอด 24/7',
    'hero.badge3': 'ผู้เชี่ยวชาญที่ได้รับการรับรอง',
    'hero.cta.book': 'จองเลย',
    'hero.cta.chat': 'แชทบน WhatsApp',

    // Service Choice
    'service.title': 'เลือกประสบการณ์พรีเมียมของคุณ',
    'service.subtitle': 'บริการที่ปรับแต่งตามความต้องการเฉพาะของคุณในเกาหลี',
    'service.medical.title': 'การดูแลทางการแพทย์และการฟื้นตัว',
    'service.medical.description': 'รับส่งที่ปลอดภัย คนขับรอในระหว่างการผ่าตัด รถที่ผ่านการฆ่าเชื้อ บริการส่งถึงประตูบ้านพร้อมการดูแลอย่างเอาใจใส่สำหรับการเดินทางทางการแพทย์ของคุณ',
    'service.medical.feature1': 'การขนส่งทางการแพทย์มืออาชีพ',
    'service.medical.feature2': 'รถที่ผ่านการฆ่าเชื้อและทำความสะอาด',
    'service.medical.feature3': 'คนขับรอระหว่างการรักษา',
    'service.medical.feature4': 'การดูแลหลังการผ่าตัดที่สะดวกสบาย',
    'service.tour.title': 'ทัวร์ส่วนตัว VVIP',
    'service.tour.description': 'กำหนดการที่ปรับแต่งได้ กว้างขวางสำหรับกอล์ฟ/ช้อปปิ้ง คนขับพูดภาษาอังกฤษ และประสบการณ์พรีเมียมที่ปรับแต่งตามไลฟ์สไตล์ของคุณ',
    'service.tour.feature1': 'กำหนดการที่ปรับแต่งได้อย่างสมบูรณ์',
    'service.tour.feature2': 'คนขับมืออาชีพที่พูดภาษาอังกฤษ',
    'service.tour.feature3': 'ภายในหรูหราที่กว้างขวาง',
    'service.tour.feature4': 'เหมาะสำหรับกอล์ฟ ช้อปปิ้ง และทัวร์',
    'service.button': 'เรียนรู้เพิ่มเติม',

    // Vehicle Showcase
    'vehicle.title': '',
    'vehicle.name': 'เกีย คาร์นิวัล ไฮลิมูซีน',
    'vehicle.subtitle': 'สัมผัสความหรูหราที่ไม่มีใครเทียบได้กับรถ VIP ชั้นนำของเกาหลี',
    'vehicle.feature1.title': 'ที่นั่งเอนได้แบบ VIP Ottoman',
    'vehicle.feature1.description': 'ความสะดวกสบายชั้นหนึ่งพร้อมที่นั่งหรูหราปรับได',
    'vehicle.feature2.title': 'ทีวีความบันเทิง 27 นิ้ว',
    'vehicle.feature2.description': 'ระบบความบันเทิงในรถระดับพรีเมียม',
    'vehicle.feature3.title': 'Wi-Fi ฟรี',
    'vehicle.feature3.description': 'เชื่อมต่อตลอดการเดินทาง',
    'vehicle.feature4.title': 'ม่านความเป็นส่วนตัว',
    'vehicle.feature4.description': 'ความเป็นส่วนตัวอย่างสมบูรณ์เพื่อความสะดวกสบายของคุณ',
    'vehicle.feature5.title': 'ความจุท้ายรถขนาดใหญ่',
    'vehicle.feature5.description': 'พื้นที่กว้างขวางสำหรับกระเป๋าเดินทาง กระเป๋ากอล์ฟ ช้อปปิ้ง',
    'vehicle.note': '✨ รักษาและทำความสะอาดอย่างมืออาชีพก่อนการเดินทางทุกครั้ง',

    // Pricing
    'pricing.title': 'โปร่งใส',
    'pricing.highlight': 'ราคา',
    'pricing.subtitle': 'เลือกแพ็คเกจที่สมบูรณ์แบบสำหรับความต้องการของคุณ ราคาทั้งหมดเป็นดอลลาร์สหรัฐ',
    'pricing.plan1.name': 'รับส่งสนามบิน',
    'pricing.plan1.note': 'เริ่มต้นที่',
    'pricing.plan1.feature1': 'บริการต้อนรับ',
    'pricing.plan1.feature2': 'ตรงจากสนามบิน/ไปสนามบิน',
    'pricing.plan1.feature3': 'ติดตามเที่ยวบิน',
    'pricing.plan1.feature4': 'ช่วยเหลือกระเป๋าเดินทาง',
    'pricing.plan1.feature5': 'เที่ยวเดียวหรือไป-กลับ',
    'pricing.plan2.name': 'ดูแลครึ่งวัน',
    'pricing.plan2.note': '5 ชั่วโมง',
    'pricing.plan2.feature1': 'บริการสูงสุด 5 ชั่วโมง',
    'pricing.plan2.feature2': 'รวมเวลารอ',
    'pricing.plan2.feature3': 'เหมาะสำหรับการเข้ารับการรักษา',
    'pricing.plan2.feature4': 'กำหนดการที่ยืดหยุ่น',
    'pricing.plan2.feature5': 'การดูแลอย่างมืออาชีพ',
    'pricing.plan3.name': 'ทัวร์ทั้งวัน',
    'pricing.plan3.note': '10 ชั่วโมง',
    'pricing.plan3.badge': 'คุ้มค่าที่สุด',
    'pricing.plan3.feature1': 'บริการสูงสุด 10 ชั่วโมง',
    'pricing.plan3.feature2': 'รวมน้ำมันและค่าทางด่วน',
    'pricing.plan3.feature3': 'กำหนดการที่ปรับแต่งได้',
    'pricing.plan3.feature4': 'คนขับพูดภาษาอังกฤษ',
    'pricing.plan3.feature5': 'ความยืดหยุ่นสูงสุด',
    'pricing.button': 'จองเลย',
    'pricing.disclaimer': '* ราคาอาจแตกต่างกันตามระยะทาง เวลา และความต้องการเฉพาะ ติดต่อเราเพื่อขอใบเสนอราคาที่ปรับแต่งตามความต้องการของคุณ',

    // Social Proof
    'social.title': 'ได้รับความไว้วางใจจาก',
    'social.highlight': 'นักเดินทาง VIP',
    'social.subtitle': 'อย่าเชื่อแค่คำพูดของเรา - ฟังจากลูกค้าที่พึงพอใจของเรา',
    'social.stat1.number': '5,000+',
    'social.stat1.label': 'ลูกค้าที่มีความสุข',
    'social.stat2.number': '10+',
    'social.stat2.label': 'ปีของประสบการณ์',
    'social.stat3.number': '4.9/5',
    'social.stat3.label': 'คะแนนเฉลี่ย',
    'social.stat4.number': '24/7',
    'social.stat4.label': 'การสนับสนุนที่มี',
    'social.review1.text': 'คนขับที่ดีที่สุดสำหรับการเดินทางผ่าตัดของฉัน การดูแลและความใส่ใจในช่วงฟื้นตัวของฉันยอดเยี่ยม แนะนำอย่างยิ่ง!',
    'social.review1.name': 'ซาราห์ จอห์นสัน',
    'social.review1.location': 'สหรัฐอเมริกา',
    'social.review2.text': 'สะดวกสบายมากสำหรับครอบครัวของฉัน ภายในที่กว้างขวางและระบบความบันเทิงทำให้ลูกๆ ของฉันมีความสุขตลอดทริป',
    'social.review2.name': 'ไมเคิล เฉิน',
    'social.review2.location': 'สิงคโปร์',
    'social.review3.text': 'มืออาชีพ ตรงต่อเวลา และหรูหรา คนขับที่พูดภาษาอังกฤษทำให้การเดินทางในเกาหลีง่ายขึ้นมาก จะใช้อีก!',
    'social.review3.name': 'เอ็มมา วิลสัน',
    'social.review3.location': 'สหราชอาณาจักร',
    'social.review4.text': 'เหมาะสำหรับทริปกอล์ฟของฉัน มีพื้นที่เพียงพอสำหรับไม้กอล์ฟและกระเป๋า คนขับรู้จักสนามและร้านอาหารที่ดีที่สุดทั้งหมด',
    'social.review4.name': 'เดวิด พาร์ค',
    'social.review4.location': 'ออสเตรเลีย',
    'social.trust1.label': 'ได้รับการยืนยันบน',
    'social.trust1.name': 'Google Reviews',
    'social.trust2.label': 'แนะนำบน',
    'social.trust2.name': 'TripAdvisor',
    'social.trust3.label': 'ได้รับความไว้วางใจโดย',
    'social.trust3.name': 'สมาคมการท่องเที่ยวเพื่อสุขภาพ',

    // Footer
    'footer.description': 'บริการคอนเซียร์จพรีเมียมที่ให้บริการขนส่งหรูหราสำหรับนักท่องเที่ยวเพื่อสุขภาพและนักเดินทาง VIP ในเกาหลี',
    'footer.quicklinks': 'ลิงก์ด่วน',
    'footer.link1': 'เกี่ยวกับเรา',
    'footer.link2': 'บริการ',
    'footer.link3': 'ราคา',
    'footer.link4': 'จองเลย',
    'footer.link5': 'คำถามที่พบบ่อย',
    'footer.services': 'บริการของเรา',
    'footer.service1': 'รับส่งสนามบิน',
    'footer.service2': 'ขนส่งดูแลทางการแพทย์',
    'footer.service3': 'ทัวร์ส่วนตัว VVIP',
    'footer.service4': 'ทัวร์กอล์ฟ',
    'footer.service5': 'ทัวร์ช้อปปิ้ง',
    'footer.contact': 'ติดต่อเรา',
    'footer.location': 'โซล, เกาหลีใต้',
    'footer.copyright': '© 2024 K-VVIPลิมูซีน สงวนลิขสิทธิ์',
    'footer.privacy': 'นโยบายความเป็นส่วนตัว',
    'footer.terms': 'ข้อกำหนดการให้บริการ',
    'footer.cookies': 'นโยบายคุกกี้',

    // Floating Chat
    'chat.inquiry': 'สอบถาม',

    // VIP Perks
    'vip.title': 'เฉพาะสำหรับลูกค้า VIP ของเรา',
    'vip.subtitle': 'สัมผัสประสบการณ์ที่มากกว่าการขนส่งในเกาหลี',
    'vip.perk1.title': 'ชุดฟื้นตัว',
    'vip.perk1.description': 'ชุดฟื้นตัวฟรีที่รวมถึงชาลดน้ำบวม, หน้ากากเย็น, และอื่นๆ',
    'vip.perk2.title': 'ทานอาหารโดยไม่ต้องรอคอย',
    'vip.perk2.description': 'ข้ามคิวที่ร้านอาหารชื่อดัง - เราจะจัดการการจอง (ганจังเกจัง, BBQ โอมาคาซี)',
    'vip.perk3.title': 'บอโทกซ์, สกินเรย์เซอร์ฟรี',
    'vip.perk3.description': 'รับบริการฟรีจากคลินิกที่ดีที่สุดในเซาโล่ - 1การรักษาฟรีต่อคน'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}